[package]
name = "byokey-translate"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
byokey-types.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json = "1"
